"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../defisheye']
DATA_FILES = ['../config']
OPTIONS = {'argv_emulation': True,
	   'packages': 'PySide,yaml',
	   'includes': 'cv,cv2',
	   'argv_inject': '--gui',
	   'iconfile': 'icon.icns',
	   }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
